<?php

/**
 * @file
 * Module file for Site Studio Extras Module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_form_alter().
 */
function sitestudio_extras_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Add only to admin pages.
  // We add to all admin pages as we do not have control over
  // where the component form would be displayed.
  if (!\Drupal::service('router.admin_context')->isAdminRoute()) {
    return;
  }
  // Check for user permission to Site Studio Elements - Custom elements group.
  if (!\Drupal::currentUser()->hasPermission('access custom elements group')) {
    return;
  }

  // Attach JS library for liraries Autocomplete feature.
  $form['#attached']['library'][] = 'sitestudio_extras/autocomplete';
  // Get list of libraries from active modules/themes.
  $libraries = \Drupal::service('sitestudio_extras.get_libraries_list')->getData();
  // Pass the libraries to the JS.
  $form['#attached']['drupalSettings']['sitestudio_extras']['libraries'] = $libraries;
}

/**
 * Implements hook_help().
 */
function sitestudio_extras_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cohesion_templates module.
    case 'help.page.example_element':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module is an example of how a developer can create a custom element. The element will be available to use in the sidebar browser and will have a form and output defined by the developer.') . '</p>';
      $output .= '<p><ul>';
      $output .= '  <li>Sample implementation of CustomElementPluginBase plugin to define a element for an render function.</li>';
      $output .= '  <li>Sample render function using form data defined in the plugin and returned by the Site Studio API.</li>';
      $output .= '</ul></p>';
      $output .= "<p>For details on how ot create a custom element, see modules/example_element/README.md</p>";
      $output .= '<p><a href="https://sitestudiodocs.acquia.com/" target="_blank">https://sitestudiodocs.acquia.com/</a></p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function sitestudio_extras_theme($existing, $type, $theme, $path) {
  return [
    'sitestudio_view_element_template' => [
      'variables' => [
        'elementSettings' => NULL,
        'elementMarkup' => NULL,
        'elementContext' => NULL,
        'elementClass' => NULL,
        'sitestudioViewElement' => NULL,
      ],
      'render element' => 'children',
    ],
  ];
}
